mod effects;
mod protocol;
mod theming;
mod tree;
mod widgets;

use std::collections::{HashMap, HashSet};
use std::io::{self, BufRead, Write};
use std::sync::mpsc::{self, Receiver, Sender};
use std::thread;
use std::time::Duration;

use iced::widget::{combo_box, container, markdown, text, text_editor};
use iced::{event, system, time, window, Element, Fill, Point, Size, Subscription, Task, Theme};

use protocol::{IncomingMessage, KeyModifiers, OutgoingEvent};
use tree::Tree;

// ---------------------------------------------------------------------------
// Message
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum Message {
    /// A user clicked a button with the given node ID.
    Click(String),
    /// A text input value changed (id, new_value).
    Input(String, String),
    /// A text input was submitted (id, current_value).
    Submit(String, String),
    /// A checkbox or toggler was toggled (id, checked).
    Toggle(String, bool),
    /// A slider value changed (id, value).
    Slide(String, f64),
    /// A slider was released (id, value).
    SlideRelease(String, f64),
    /// A pick_list/combo_box/radio selection (id, value).
    Select(String, String),
    /// A text editor action (id, action).
    TextEditorAction(String, text_editor::Action),
    /// A markdown link was clicked.
    MarkdownUrl(markdown::Uri),
    /// Periodic tick used to drain the inbound channel.
    Tick,
    /// A keyboard key was pressed.
    KeyPressed(iced::keyboard::Key, iced::keyboard::Modifiers),
    /// A keyboard key was released.
    KeyReleased(iced::keyboard::Key, iced::keyboard::Modifiers),
    /// Keyboard modifiers changed.
    ModifiersChanged(iced::keyboard::Modifiers),
    /// A window close was requested by the user (WM close button).
    WindowCloseRequested(window::Id),
    /// A window was actually closed by iced.
    WindowClosed(window::Id),
    /// A new window was opened (iced_id, julep_id).
    WindowOpened(window::Id, String),
    // -- Mouse events --
    /// Cursor moved to (x, y) in a window.
    CursorMoved(Point, window::Id),
    /// Cursor entered a window.
    CursorEntered(window::Id),
    /// Cursor left a window.
    CursorLeft(window::Id),
    /// Mouse button pressed.
    MouseButtonPressed(iced::mouse::Button, window::Id),
    /// Mouse button released.
    MouseButtonReleased(iced::mouse::Button, window::Id),
    /// Mouse wheel scrolled.
    WheelScrolled(iced::mouse::ScrollDelta, window::Id),
    // -- Touch events --
    /// Touch finger pressed.
    FingerPressed(iced::touch::Finger, Point, window::Id),
    /// Touch finger moved.
    FingerMoved(iced::touch::Finger, Point, window::Id),
    /// Touch finger lifted.
    FingerLifted(iced::touch::Finger, Point, window::Id),
    /// Touch finger lost.
    FingerLost(iced::touch::Finger, Point, window::Id),
    // -- Window lifecycle events --
    /// A window event from iced (window_id, event).
    WindowEvent(window::Id, window::Event),
    // -- System / animation events --
    /// Animation frame with timestamp.
    AnimationFrame(iced::time::Instant),
    /// System theme mode changed.
    ThemeChanged(iced::theme::Mode),
}

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct App {
    tree: Tree,
    theme: Theme,
    receiver: Receiver<StdinEvent>,
    stdin_closed: bool,
    /// Persistent state for text_editor widgets, keyed by node ID.
    editor_contents: HashMap<String, text_editor::Content>,
    /// Cached parsed markdown items, keyed by node ID.
    markdown_items: HashMap<String, Vec<markdown::Item>>,
    /// Persistent combo_box states, keyed by node ID.
    combo_states: HashMap<String, combo_box::State<String>>,
    /// Tasks generated by apply() that must be returned from update().
    pending_tasks: Vec<Task<Message>>,
    /// Active subscriptions: kind -> tag.
    active_subscriptions: HashMap<String, String>,
    /// Julep window ID -> iced window ID.
    window_map: HashMap<String, window::Id>,
    /// Iced window ID -> julep window ID.
    reverse_window_map: HashMap<window::Id, String>,
}

/// What the stdin reader thread sends back.
#[derive(Debug)]
enum StdinEvent {
    Message(IncomingMessage),
    Closed,
    Warning(String),
}

impl App {
    fn new(receiver: Receiver<StdinEvent>) -> Self {
        Self {
            tree: Tree::new(),
            theme: Theme::Dark,
            receiver,
            stdin_closed: false,
            editor_contents: HashMap::new(),
            markdown_items: HashMap::new(),
            combo_states: HashMap::new(),
            pending_tasks: Vec::new(),
            active_subscriptions: HashMap::new(),
            window_map: HashMap::new(),
            reverse_window_map: HashMap::new(),
        }
    }

    fn title_for_window(&self, window_id: window::Id) -> String {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id) {
            if let Some(node) = self.tree.find_window(julep_id) {
                if let Some(title) = node.props.get("title").and_then(|v| v.as_str()) {
                    return title.to_string();
                }
            }
        }
        "Julep".to_string()
    }

    fn theme_for_window(&self, window_id: window::Id) -> Theme {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id) {
            if let Some(node) = self.tree.find_window(julep_id) {
                if let Some(theme_val) = node.props.get("theme") {
                    return theming::resolve_theme_only(theme_val);
                }
            }
        }
        self.theme.clone()
    }

    /// Resolve a julep window ID string from an iced window::Id.
    fn julep_id_for(&self, iced_id: &window::Id) -> String {
        self.reverse_window_map
            .get(iced_id)
            .cloned()
            .unwrap_or_default()
    }

    fn update(&mut self, message: Message) -> Task<Message> {
        match message {
            Message::Tick => {
                self.drain_stdin();
                let tasks: Vec<Task<Message>> = self.pending_tasks.drain(..).collect();
                let mut batch = Task::batch(tasks);
                if self.stdin_closed {
                    batch = batch.chain(iced::exit());
                }
                batch
            }
            Message::Click(id) => {
                emit_event(OutgoingEvent::click(id));
                Task::none()
            }
            Message::Input(id, value) => {
                emit_event(OutgoingEvent::input(id, value));
                Task::none()
            }
            Message::Submit(id, value) => {
                emit_event(OutgoingEvent::submit(id, value));
                Task::none()
            }
            Message::Toggle(id, value) => {
                emit_event(OutgoingEvent::toggle(id, value));
                Task::none()
            }
            Message::Slide(id, value) => {
                emit_event(OutgoingEvent::slide(id, value));
                Task::none()
            }
            Message::SlideRelease(id, value) => {
                emit_event(OutgoingEvent::slide_release(id, value));
                Task::none()
            }
            Message::Select(id, value) => {
                emit_event(OutgoingEvent::select(id, value));
                Task::none()
            }
            Message::TextEditorAction(id, action) => {
                let is_edit = action.is_edit();
                if let Some(content) = self.editor_contents.get_mut(&id) {
                    content.perform(action);
                    if is_edit {
                        let new_text = content.text();
                        emit_event(OutgoingEvent::input(id, new_text));
                    }
                }
                Task::none()
            }
            Message::MarkdownUrl(url) => {
                eprintln!("julep_gui: markdown link clicked: {url}");
                Task::none()
            }

            // -- Keyboard events --
            Message::KeyPressed(key, mods) => {
                if let Some(tag) = self.active_subscriptions.get("on_key_press") {
                    let key_str = serialize_key(&key);
                    emit_event(OutgoingEvent::key_press(
                        tag.clone(),
                        key_str,
                        serialize_modifiers(mods),
                    ));
                }
                Task::none()
            }
            Message::KeyReleased(key, mods) => {
                if let Some(tag) = self.active_subscriptions.get("on_key_release") {
                    let key_str = serialize_key(&key);
                    emit_event(OutgoingEvent::key_release(
                        tag.clone(),
                        key_str,
                        serialize_modifiers(mods),
                    ));
                }
                Task::none()
            }
            Message::ModifiersChanged(mods) => {
                if let Some(tag) = self.active_subscriptions.get("on_modifiers_changed") {
                    emit_event(OutgoingEvent::modifiers_changed(
                        tag.clone(),
                        serialize_modifiers(mods),
                    ));
                }
                Task::none()
            }

            // -- Mouse events --
            Message::CursorMoved(pos, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_move") {
                    emit_event(OutgoingEvent::cursor_moved(tag.clone(), pos.x, pos.y));
                }
                Task::none()
            }
            Message::CursorEntered(_win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_move") {
                    emit_event(OutgoingEvent::cursor_entered(tag.clone()));
                }
                Task::none()
            }
            Message::CursorLeft(_win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_move") {
                    emit_event(OutgoingEvent::cursor_left(tag.clone()));
                }
                Task::none()
            }
            Message::MouseButtonPressed(button, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_button") {
                    emit_event(OutgoingEvent::button_pressed(
                        tag.clone(),
                        serialize_mouse_button(&button),
                    ));
                }
                Task::none()
            }
            Message::MouseButtonReleased(button, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_button") {
                    emit_event(OutgoingEvent::button_released(
                        tag.clone(),
                        serialize_mouse_button(&button),
                    ));
                }
                Task::none()
            }
            Message::WheelScrolled(delta, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_mouse_scroll") {
                    let (dx, dy, unit) = serialize_scroll_delta(&delta);
                    emit_event(OutgoingEvent::wheel_scrolled(tag.clone(), dx, dy, unit));
                }
                Task::none()
            }

            // -- Touch events --
            Message::FingerPressed(finger, pos, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_touch") {
                    emit_event(OutgoingEvent::finger_pressed(
                        tag.clone(),
                        finger.0,
                        pos.x,
                        pos.y,
                    ));
                }
                Task::none()
            }
            Message::FingerMoved(finger, pos, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_touch") {
                    emit_event(OutgoingEvent::finger_moved(
                        tag.clone(),
                        finger.0,
                        pos.x,
                        pos.y,
                    ));
                }
                Task::none()
            }
            Message::FingerLifted(finger, pos, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_touch") {
                    emit_event(OutgoingEvent::finger_lifted(
                        tag.clone(),
                        finger.0,
                        pos.x,
                        pos.y,
                    ));
                }
                Task::none()
            }
            Message::FingerLost(finger, pos, _win) => {
                if let Some(tag) = self.active_subscriptions.get("on_touch") {
                    emit_event(OutgoingEvent::finger_lost(
                        tag.clone(),
                        finger.0,
                        pos.x,
                        pos.y,
                    ));
                }
                Task::none()
            }

            // -- Window lifecycle events --
            Message::WindowCloseRequested(window_id) => {
                if let Some(tag) = self.active_subscriptions.get("on_window_close") {
                    let julep_id = self.julep_id_for(&window_id);
                    emit_event(OutgoingEvent::window_close_requested(
                        tag.clone(),
                        julep_id,
                    ));
                }
                // Remove from maps if this was a julep-managed window.
                if let Some(julep_id) = self.reverse_window_map.remove(&window_id) {
                    self.window_map.remove(&julep_id);
                }
                window::close(window_id)
            }
            Message::WindowClosed(window_id) => {
                // Clean up maps when iced confirms a window has closed.
                if let Some(julep_id) = self.reverse_window_map.remove(&window_id) {
                    self.window_map.remove(&julep_id);
                    if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                        emit_event(OutgoingEvent::window_closed(tag.clone(), julep_id.clone()));
                    }
                    eprintln!("julep_gui: window closed: {julep_id}");
                }
                // All managed windows gone -- exit cleanly.
                if self.window_map.is_empty() {
                    eprintln!("julep_gui: all windows closed -- exiting");
                    iced::exit()
                } else {
                    Task::none()
                }
            }
            Message::WindowOpened(iced_id, julep_id) => {
                eprintln!("julep_gui: window opened: {julep_id} -> {iced_id:?}");
                self.window_map.insert(julep_id.clone(), iced_id);
                self.reverse_window_map.insert(iced_id, julep_id);
                Task::none()
            }
            Message::WindowEvent(iced_id, evt) => {
                let julep_id = self.julep_id_for(&iced_id);
                match evt {
                    window::Event::Opened { position, size } => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            let pos = position.map(|p| (p.x, p.y));
                            emit_event(OutgoingEvent::window_opened(
                                tag.clone(),
                                julep_id,
                                pos,
                                size.width,
                                size.height,
                            ));
                        }
                    }
                    window::Event::Closed => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_closed(tag.clone(), julep_id));
                        }
                    }
                    window::Event::Moved(point) => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_moved(
                                tag.clone(),
                                julep_id,
                                point.x,
                                point.y,
                            ));
                        }
                    }
                    window::Event::Resized(size) => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_resized(
                                tag.clone(),
                                julep_id,
                                size.width,
                                size.height,
                            ));
                        }
                    }
                    window::Event::Rescaled(factor) => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_rescaled(
                                tag.clone(),
                                julep_id,
                                factor,
                            ));
                        }
                    }
                    window::Event::Focused => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_focused(tag.clone(), julep_id));
                        }
                    }
                    window::Event::Unfocused => {
                        if let Some(tag) = self.active_subscriptions.get("on_window_event") {
                            emit_event(OutgoingEvent::window_unfocused(tag.clone(), julep_id));
                        }
                    }
                    window::Event::FileHovered(path) => {
                        if let Some(tag) = self.active_subscriptions.get("on_file_drop") {
                            emit_event(OutgoingEvent::file_hovered(
                                tag.clone(),
                                julep_id,
                                path.to_string_lossy().to_string(),
                            ));
                        }
                    }
                    window::Event::FileDropped(path) => {
                        if let Some(tag) = self.active_subscriptions.get("on_file_drop") {
                            emit_event(OutgoingEvent::file_dropped(
                                tag.clone(),
                                julep_id,
                                path.to_string_lossy().to_string(),
                            ));
                        }
                    }
                    window::Event::FilesHoveredLeft => {
                        if let Some(tag) = self.active_subscriptions.get("on_file_drop") {
                            emit_event(OutgoingEvent::files_hovered_left(tag.clone(), julep_id));
                        }
                    }
                    window::Event::CloseRequested => {
                        // Handled via close_requests() subscription separately.
                    }
                    window::Event::RedrawRequested(_) => {
                        // Handled via animation_frame subscription separately.
                    }
                }
                Task::none()
            }

            // -- System / animation --
            Message::AnimationFrame(instant) => {
                if let Some(tag) = self.active_subscriptions.get("on_animation_frame") {
                    // Convert Instant to a duration since some epoch. We use
                    // elapsed from the process start as a monotonic timestamp.
                    let millis = instant
                        .duration_since(iced::time::Instant::now() - instant.elapsed())
                        .as_millis();
                    emit_event(OutgoingEvent::animation_frame(tag.clone(), millis));
                }
                Task::none()
            }
            Message::ThemeChanged(mode) => {
                if let Some(tag) = self.active_subscriptions.get("on_theme_change") {
                    let mode_str = match mode {
                        iced::theme::Mode::Light => "light",
                        iced::theme::Mode::Dark => "dark",
                        _ => "system",
                    };
                    emit_event(OutgoingEvent::theme_changed(
                        tag.clone(),
                        mode_str.to_string(),
                    ));
                }
                Task::none()
            }
        }
    }

    fn view_window(&self, window_id: window::Id) -> Element<'_, Message> {
        let julep_id = match self.reverse_window_map.get(&window_id) {
            Some(id) => id,
            None => {
                return container(text("unknown window"))
                    .width(Fill)
                    .height(Fill)
                    .center(Fill)
                    .into();
            }
        };

        match self.tree.find_window(julep_id) {
            Some(window_node) => {
                widgets::render(window_node, &self.editor_contents, &self.markdown_items, &self.combo_states)
            }
            None => container(text("waiting for snapshot..."))
                .width(Fill)
                .height(Fill)
                .center(Fill)
                .into(),
        }
    }

    fn subscription(&self) -> Subscription<Message> {
        let mut subs = vec![
            time::every(Duration::from_millis(16)).map(|_| Message::Tick),
            // Always listen for window close events so we can clean up maps.
            window::close_events().map(Message::WindowClosed),
        ];

        // -- Keyboard subscriptions --
        if self.active_subscriptions.contains_key("on_key_press") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyPressed {
                    key,
                    modifiers,
                    ..
                }) = evt
                {
                    Some(Message::KeyPressed(key, modifiers))
                } else {
                    None
                }
            }));
        }

        if self.active_subscriptions.contains_key("on_key_release") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyReleased {
                    key,
                    modifiers,
                    ..
                }) = evt
                {
                    Some(Message::KeyReleased(key, modifiers))
                } else {
                    None
                }
            }));
        }

        if self.active_subscriptions.contains_key("on_modifiers_changed") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::ModifiersChanged(mods)) = evt {
                    Some(Message::ModifiersChanged(mods))
                } else {
                    None
                }
            }));
        }

        // -- Mouse subscriptions --
        if self.active_subscriptions.contains_key("on_mouse_move") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Mouse(iced::mouse::Event::CursorMoved { position }) => {
                    Some(Message::CursorMoved(position, window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorEntered) => {
                    Some(Message::CursorEntered(window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorLeft) => {
                    Some(Message::CursorLeft(window))
                }
                _ => None,
            }));
        }

        if self.active_subscriptions.contains_key("on_mouse_button") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Mouse(iced::mouse::Event::ButtonPressed(button)) => {
                    Some(Message::MouseButtonPressed(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonReleased(button)) => {
                    Some(Message::MouseButtonReleased(button, window))
                }
                _ => None,
            }));
        }

        if self.active_subscriptions.contains_key("on_mouse_scroll") {
            subs.push(event::listen_with(|evt, _status, window| {
                if let iced::Event::Mouse(iced::mouse::Event::WheelScrolled { delta }) = evt {
                    Some(Message::WheelScrolled(delta, window))
                } else {
                    None
                }
            }));
        }

        // -- Touch subscriptions --
        if self.active_subscriptions.contains_key("on_touch") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                iced::Event::Touch(iced::touch::Event::FingerPressed { id, position }) => {
                    Some(Message::FingerPressed(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerMoved { id, position }) => {
                    Some(Message::FingerMoved(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLifted { id, position }) => {
                    Some(Message::FingerLifted(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLost { id, position }) => {
                    Some(Message::FingerLost(id, position, window))
                }
                _ => None,
            }));
        }

        // -- Window event subscriptions --
        if self.active_subscriptions.contains_key("on_window_event")
            || self.active_subscriptions.contains_key("on_file_drop")
        {
            subs.push(window::events().map(|(id, evt)| Message::WindowEvent(id, evt)));
        }

        if self.active_subscriptions.contains_key("on_window_close") {
            subs.push(window::close_requests().map(Message::WindowCloseRequested));
        }

        // -- Animation frame subscription --
        if self.active_subscriptions.contains_key("on_animation_frame") {
            subs.push(window::frames().map(Message::AnimationFrame));
        }

        // -- System theme change subscription --
        if self.active_subscriptions.contains_key("on_theme_change") {
            subs.push(system::theme_changes().map(Message::ThemeChanged));
        }

        // -- Catch-all event subscription --
        // Subscribes to all keyboard, mouse, and touch events via a single
        // listener, re-using existing Message variants. Window events are
        // handled separately by on_window_event.
        if self.active_subscriptions.contains_key("on_event") {
            subs.push(event::listen_with(|evt, _status, window| match evt {
                // Keyboard
                iced::Event::Keyboard(iced::keyboard::Event::KeyPressed {
                    key, modifiers, ..
                }) => Some(Message::KeyPressed(key, modifiers)),
                iced::Event::Keyboard(iced::keyboard::Event::KeyReleased {
                    key, modifiers, ..
                }) => Some(Message::KeyReleased(key, modifiers)),
                iced::Event::Keyboard(iced::keyboard::Event::ModifiersChanged(mods)) => {
                    Some(Message::ModifiersChanged(mods))
                }
                // Mouse
                iced::Event::Mouse(iced::mouse::Event::CursorMoved { position }) => {
                    Some(Message::CursorMoved(position, window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorEntered) => {
                    Some(Message::CursorEntered(window))
                }
                iced::Event::Mouse(iced::mouse::Event::CursorLeft) => {
                    Some(Message::CursorLeft(window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonPressed(button)) => {
                    Some(Message::MouseButtonPressed(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::ButtonReleased(button)) => {
                    Some(Message::MouseButtonReleased(button, window))
                }
                iced::Event::Mouse(iced::mouse::Event::WheelScrolled { delta }) => {
                    Some(Message::WheelScrolled(delta, window))
                }
                // Touch
                iced::Event::Touch(iced::touch::Event::FingerPressed { id, position }) => {
                    Some(Message::FingerPressed(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerMoved { id, position }) => {
                    Some(Message::FingerMoved(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLifted { id, position }) => {
                    Some(Message::FingerLifted(id, position, window))
                }
                iced::Event::Touch(iced::touch::Event::FingerLost { id, position }) => {
                    Some(Message::FingerLost(id, position, window))
                }
                // Window events handled by on_window_event
                _ => None,
            }));
        }

        Subscription::batch(subs)
    }

    /// Drain all pending messages from the stdin channel and apply them.
    fn drain_stdin(&mut self) {
        loop {
            match self.receiver.try_recv() {
                Ok(StdinEvent::Message(incoming)) => {
                    self.apply(incoming);
                }
                Ok(StdinEvent::Warning(msg)) => {
                    eprintln!("julep_gui: stdin warning: {msg}");
                }
                Ok(StdinEvent::Closed) => {
                    eprintln!("julep_gui: stdin closed -- exiting");
                    self.stdin_closed = true;
                    break;
                }
                Err(mpsc::TryRecvError::Empty) => break,
                Err(mpsc::TryRecvError::Disconnected) => {
                    eprintln!("julep_gui: stdin reader disconnected -- exiting");
                    self.stdin_closed = true;
                    break;
                }
            }
        }
    }

    fn apply(&mut self, message: IncomingMessage) {
        match message {
            IncomingMessage::Snapshot { tree } => {
                eprintln!("julep_gui: snapshot received (root id={})", tree.id);
                if let Some(theme_val) = tree.props.get("theme") {
                    self.theme = theming::resolve_theme_only(theme_val);
                }
                self.tree.snapshot(tree);
                // Clear stale caches and pre-populate for the new tree.
                self.editor_contents.clear();
                self.markdown_items.clear();
                self.combo_states.clear();
                if let Some(root) = self.tree.root() {
                    widgets::ensure_caches(
                        root,
                        &mut self.editor_contents,
                        &mut self.markdown_items,
                        &mut self.combo_states,
                    );
                }
                // Sync windows to match the new tree.
                let task = self.sync_windows();
                self.pending_tasks.push(task);
            }
            IncomingMessage::Patch { ops } => {
                eprintln!("julep_gui: patch received ({} ops)", ops.len());
                self.tree.apply_patch(ops);
                // Re-populate caches in case patch added new stateful nodes.
                if let Some(root) = self.tree.root() {
                    widgets::ensure_caches(
                        root,
                        &mut self.editor_contents,
                        &mut self.markdown_items,
                        &mut self.combo_states,
                    );
                }
                // Sync windows in case the patch changed the window set.
                let task = self.sync_windows();
                self.pending_tasks.push(task);
            }
            IncomingMessage::EffectRequest { id, kind, payload } => {
                eprintln!("julep_gui: effect request: {kind} ({id})");
                let response = effects::handle_effect(id, &kind, &payload);
                emit_effect_response(response);
            }
            IncomingMessage::WidgetOp { op, payload } => {
                eprintln!("julep_gui: widget_op: {op}");
                let task = self.handle_widget_op(&op, &payload);
                self.pending_tasks.push(task);
            }
            IncomingMessage::SubscriptionRegister { kind, tag } => {
                eprintln!("julep_gui: subscription register: {kind} -> {tag}");
                self.active_subscriptions.insert(kind, tag);
            }
            IncomingMessage::SubscriptionUnregister { kind } => {
                eprintln!("julep_gui: subscription unregister: {kind}");
                self.active_subscriptions.remove(&kind);
            }
            IncomingMessage::WindowOp {
                op,
                window_id,
                settings,
            } => {
                eprintln!("julep_gui: window_op: {op} ({window_id})");
                let task = self.handle_window_op(&op, &window_id, &settings);
                self.pending_tasks.push(task);
            }
        }
    }

    // -----------------------------------------------------------------------
    // Widget operations
    // -----------------------------------------------------------------------

    fn handle_widget_op(&mut self, op: &str, payload: &serde_json::Value) -> Task<Message> {
        let get_target = || {
            payload
                .get("target")
                .and_then(|v| v.as_str())
                .unwrap_or_default()
                .to_string()
        };

        match op {
            "focus" => {
                iced::widget::operation::focus::<Message>(iced::widget::Id::from(get_target()))
            }
            "focus_next" => iced::widget::operation::focus_next(),
            "focus_previous" => iced::widget::operation::focus_previous(),
            "scroll_to" => {
                let target = get_target();
                let offset_x = payload
                    .get("offset_x")
                    .and_then(|v| v.as_f64())
                    .map(|v| v as f32);
                let offset_y = payload
                    .get("offset")
                    .or_else(|| payload.get("offset_y"))
                    .and_then(|v| v.as_f64())
                    .map(|v| v as f32);
                iced::widget::operation::scroll_to(
                    iced::widget::Id::from(target),
                    iced::widget::operation::AbsoluteOffset {
                        x: offset_x.unwrap_or(0.0),
                        y: offset_y.unwrap_or(0.0),
                    },
                )
            }
            "scroll_by" => {
                let target = get_target();
                let offset_x = payload
                    .get("offset_x")
                    .and_then(|v| v.as_f64())
                    .unwrap_or(0.0) as f32;
                let offset_y = payload
                    .get("offset_y")
                    .and_then(|v| v.as_f64())
                    .unwrap_or(0.0) as f32;
                iced::widget::operation::scroll_by(
                    iced::widget::Id::from(target),
                    iced::widget::operation::AbsoluteOffset {
                        x: offset_x,
                        y: offset_y,
                    },
                )
            }
            "snap_to" => {
                let target = get_target();
                let x = payload
                    .get("x")
                    .and_then(|v| v.as_f64())
                    .map(|v| v as f32);
                let y = payload
                    .get("y")
                    .and_then(|v| v.as_f64())
                    .map(|v| v as f32);
                iced::widget::operation::snap_to(
                    iced::widget::Id::from(target),
                    iced::widget::operation::RelativeOffset { x, y },
                )
            }
            "snap_to_end" => {
                let target = get_target();
                iced::widget::operation::snap_to_end(iced::widget::Id::from(target))
            }
            "select_all" => {
                iced::widget::operation::select_all(iced::widget::Id::from(get_target()))
            }
            "select_range" => {
                let target = get_target();
                let start = payload
                    .get("start")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(0) as usize;
                let end = payload
                    .get("end")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(0) as usize;
                iced::widget::operation::select_range(iced::widget::Id::from(target), start, end)
            }
            "move_cursor_to_front" => {
                iced::widget::operation::move_cursor_to_front(iced::widget::Id::from(get_target()))
            }
            "move_cursor_to_end" => {
                iced::widget::operation::move_cursor_to_end(iced::widget::Id::from(get_target()))
            }
            "move_cursor_to" => {
                let target = get_target();
                let position = payload
                    .get("position")
                    .and_then(|v| v.as_u64())
                    .unwrap_or(0) as usize;
                iced::widget::operation::move_cursor_to(
                    iced::widget::Id::from(target),
                    position,
                )
            }
            "close_window" => {
                // Close the oldest (main) window, which triggers app exit.
                window::oldest().and_then(|id| window::close(id))
            }
            "exit" => iced::exit(),
            other => {
                eprintln!("julep_gui: unknown widget_op: {other}");
                Task::none()
            }
        }
    }

    // -----------------------------------------------------------------------
    // Window operations
    // -----------------------------------------------------------------------

    fn handle_window_op(
        &mut self,
        op: &str,
        window_id: &str,
        settings: &serde_json::Value,
    ) -> Task<Message> {
        match op {
            "open" => {
                if self.window_map.contains_key(window_id) {
                    eprintln!(
                        "julep_gui: window_op open: {window_id} already open, skipping"
                    );
                    return Task::none();
                }

                let win_settings = parse_window_settings(settings);
                let (iced_id, open_task) = window::open(win_settings);

                self.window_map.insert(window_id.to_string(), iced_id);
                self.reverse_window_map
                    .insert(iced_id, window_id.to_string());

                let julep_id = window_id.to_string();
                open_task.map(move |id| Message::WindowOpened(id, julep_id.clone()))
            }
            "close" => {
                if let Some(iced_id) = self.window_map.remove(window_id) {
                    self.reverse_window_map.remove(&iced_id);
                    window::close(iced_id)
                } else {
                    eprintln!("julep_gui: window_op close: unknown window_id: {window_id}");
                    Task::none()
                }
            }
            "resize" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let w = settings
                        .get("width")
                        .and_then(|v| v.as_f64())
                        .unwrap_or(800.0) as f32;
                    let h = settings
                        .get("height")
                        .and_then(|v| v.as_f64())
                        .unwrap_or(600.0) as f32;
                    window::resize(iced_id, Size::new(w, h))
                } else {
                    Task::none()
                }
            }
            "move" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let x = settings
                        .get("x")
                        .and_then(|v| v.as_f64())
                        .unwrap_or(0.0) as f32;
                    let y = settings
                        .get("y")
                        .and_then(|v| v.as_f64())
                        .unwrap_or(0.0) as f32;
                    window::move_to(iced_id, Point::new(x, y))
                } else {
                    Task::none()
                }
            }
            "maximize" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let maximized = settings
                        .get("maximized")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(true);
                    window::maximize(iced_id, maximized)
                } else {
                    Task::none()
                }
            }
            "minimize" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let minimized = settings
                        .get("minimized")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(true);
                    window::minimize(iced_id, minimized)
                } else {
                    Task::none()
                }
            }
            "set_mode" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let mode = parse_window_mode(settings);
                    window::set_mode(iced_id, mode)
                } else {
                    Task::none()
                }
            }
            "toggle_maximize" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    window::toggle_maximize(iced_id)
                } else {
                    Task::none()
                }
            }
            "toggle_decorations" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    window::toggle_decorations(iced_id)
                } else {
                    Task::none()
                }
            }
            "gain_focus" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    window::gain_focus(iced_id)
                } else {
                    Task::none()
                }
            }
            "set_level" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let level = parse_window_level(
                        settings
                            .get("level")
                            .and_then(|v| v.as_str())
                            .unwrap_or("normal"),
                    );
                    window::set_level(iced_id, level)
                } else {
                    Task::none()
                }
            }
            "drag" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    window::drag(iced_id)
                } else {
                    Task::none()
                }
            }
            "drag_resize" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let direction = parse_direction(
                        settings
                            .get("direction")
                            .and_then(|v| v.as_str())
                            .unwrap_or("south_east"),
                    );
                    window::drag_resize(iced_id, direction)
                } else {
                    Task::none()
                }
            }
            "request_attention" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let urgency = settings
                        .get("urgency")
                        .and_then(|v| v.as_str())
                        .map(|s| match s {
                            "critical" => window::UserAttention::Critical,
                            _ => window::UserAttention::Informational,
                        });
                    window::request_user_attention(iced_id, urgency)
                } else {
                    Task::none()
                }
            }
            "show_system_menu" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    window::show_system_menu(iced_id)
                } else {
                    Task::none()
                }
            }
            "set_resizable" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let resizable = settings
                        .get("resizable")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(true);
                    window::set_resizable(iced_id, resizable)
                } else {
                    Task::none()
                }
            }
            "set_min_size" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let size = parse_optional_size(settings);
                    window::set_min_size(iced_id, size)
                } else {
                    Task::none()
                }
            }
            "set_max_size" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let size = parse_optional_size(settings);
                    window::set_max_size(iced_id, size)
                } else {
                    Task::none()
                }
            }
            "mouse_passthrough" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let enabled = settings
                        .get("enabled")
                        .and_then(|v| v.as_bool())
                        .unwrap_or(true);
                    if enabled {
                        window::enable_mouse_passthrough(iced_id)
                    } else {
                        window::disable_mouse_passthrough(iced_id)
                    }
                } else {
                    Task::none()
                }
            }
            // -- Query operations: return results as effect_response --
            "get_size" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::size(iced_id).map(move |size| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!({"width": size.width, "height": size.height}),
                        );
                        emit_effect_response(resp);
                        Message::Tick // dummy message to keep the type system happy
                    })
                } else {
                    Task::none()
                }
            }
            "get_position" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::position(iced_id).map(move |pos| {
                        let val = match pos {
                            Some(p) => serde_json::json!({"x": p.x, "y": p.y}),
                            None => serde_json::Value::Null,
                        };
                        let resp = protocol::EffectResponse::ok(wid.clone(), val);
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "get_mode" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::mode(iced_id).map(move |mode| {
                        let mode_str = match mode {
                            window::Mode::Windowed => "windowed",
                            window::Mode::Fullscreen => "fullscreen",
                            window::Mode::Hidden => "hidden",
                        };
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!(mode_str),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "get_scale_factor" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::scale_factor(iced_id).map(move |factor| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!(factor),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "is_maximized" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::is_maximized(iced_id).map(move |val| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!(val),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "is_minimized" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::is_minimized(iced_id).map(move |val| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!(val),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "screenshot" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::screenshot(iced_id).map(move |screenshot| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!({
                                "width": screenshot.size.width,
                                "height": screenshot.size.height,
                                "bytes_len": screenshot.rgba.len(),
                            }),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "set_icon" => {
                // Icon support requires raw RGBA pixel data and dimensions,
                // which is complex to pass over JSONL. Recognized but not yet
                // implemented.
                eprintln!("julep_gui: set_icon not yet supported (requires RGBA pixel data)");
                Task::none()
            }
            "raw_id" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::raw_id::<Message>(iced_id).map(move |raw| {
                        let resp = protocol::EffectResponse::ok(
                            wid.clone(),
                            serde_json::json!(raw),
                        );
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            "monitor_size" => {
                if let Some(&iced_id) = self.window_map.get(window_id) {
                    let wid = window_id.to_string();
                    window::monitor_size(iced_id).map(move |size_opt| {
                        let result = match size_opt {
                            Some(size) => serde_json::json!({"width": size.width, "height": size.height}),
                            None => serde_json::Value::Null,
                        };
                        let resp = protocol::EffectResponse::ok(wid.clone(), result);
                        emit_effect_response(resp);
                        Message::Tick
                    })
                } else {
                    Task::none()
                }
            }
            other => {
                eprintln!("julep_gui: unknown window_op: {other}");
                Task::none()
            }
        }
    }

    /// Compare the set of window nodes in the tree against the currently open
    /// windows and open/close as needed.
    fn sync_windows(&mut self) -> Task<Message> {
        let tree_windows: HashSet<String> = self.tree.window_ids().into_iter().collect();
        let open_windows: HashSet<String> = self.window_map.keys().cloned().collect();

        let mut tasks = Vec::new();

        // Open windows that exist in the tree but are not yet open.
        for win_id in &tree_windows {
            if !open_windows.contains(win_id) {
                let settings = self.window_settings_for(win_id);
                let (iced_id, open_task) = window::open(settings);
                self.window_map.insert(win_id.clone(), iced_id);
                self.reverse_window_map.insert(iced_id, win_id.clone());

                let julep_id = win_id.clone();
                tasks.push(
                    open_task.map(move |id| Message::WindowOpened(id, julep_id.clone())),
                );
            }
        }

        // Close windows that are open but no longer in the tree.
        for win_id in &open_windows {
            if !tree_windows.contains(win_id) {
                if let Some(iced_id) = self.window_map.remove(win_id) {
                    self.reverse_window_map.remove(&iced_id);
                    tasks.push(window::close(iced_id));
                }
            }
        }

        Task::batch(tasks)
    }

    /// Build window::Settings from a window node's props.
    fn window_settings_for(&self, julep_id: &str) -> window::Settings {
        if let Some(node) = self.tree.find_window(julep_id) {
            parse_window_settings(&node.props)
        } else {
            window::Settings {
                size: Size::new(800.0, 600.0),
                ..window::Settings::default()
            }
        }
    }
}

// ---------------------------------------------------------------------------
// Settings / enum parsing helpers
// ---------------------------------------------------------------------------

/// Parse a full `window::Settings` from a JSON value (node props or op settings).
fn parse_window_settings(v: &serde_json::Value) -> window::Settings {
    let width = v
        .get("width")
        .and_then(|v| v.as_f64())
        .unwrap_or(800.0) as f32;
    let height = v
        .get("height")
        .and_then(|v| v.as_f64())
        .unwrap_or(600.0) as f32;

    let maximized = v
        .get("maximized")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let fullscreen = v
        .get("fullscreen")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let visible = v.get("visible").and_then(|v| v.as_bool()).unwrap_or(true);
    let resizable = v
        .get("resizable")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);
    let closeable = v
        .get("closeable")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);
    let minimizable = v
        .get("minimizable")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);
    let decorations = v
        .get("decorations")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);
    let transparent = v
        .get("transparent")
        .and_then(|v| v.as_bool())
        .unwrap_or(false);
    let blur = v.get("blur").and_then(|v| v.as_bool()).unwrap_or(false);
    let exit_on_close_request = v
        .get("exit_on_close_request")
        .and_then(|v| v.as_bool())
        .unwrap_or(true);

    let position = match v.get("position") {
        Some(serde_json::Value::String(s)) if s == "centered" => window::Position::Centered,
        Some(obj) if obj.is_object() => {
            let x = obj.get("x").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            let y = obj.get("y").and_then(|v| v.as_f64()).unwrap_or(0.0) as f32;
            window::Position::Specific(Point::new(x, y))
        }
        _ => window::Position::default(),
    };

    let min_size = parse_optional_size(v.get("min_size").unwrap_or(&serde_json::Value::Null));
    let max_size = parse_optional_size(v.get("max_size").unwrap_or(&serde_json::Value::Null));

    let level = parse_window_level(
        v.get("level")
            .and_then(|v| v.as_str())
            .unwrap_or("normal"),
    );

    window::Settings {
        size: Size::new(width, height),
        maximized,
        fullscreen,
        position,
        min_size,
        max_size,
        visible,
        resizable,
        closeable,
        minimizable,
        decorations,
        transparent,
        blur,
        level,
        exit_on_close_request,
        ..window::Settings::default()
    }
}

fn parse_optional_size(v: &serde_json::Value) -> Option<Size> {
    if v.is_null() || !v.is_object() {
        // Also accept from the parent settings object directly for set_min_size/set_max_size ops
        let w = v.get("width").and_then(|v| v.as_f64());
        let h = v.get("height").and_then(|v| v.as_f64());
        match (w, h) {
            (Some(w), Some(h)) => Some(Size::new(w as f32, h as f32)),
            _ => None,
        }
    } else {
        let w = v.get("width").and_then(|v| v.as_f64());
        let h = v.get("height").and_then(|v| v.as_f64());
        match (w, h) {
            (Some(w), Some(h)) => Some(Size::new(w as f32, h as f32)),
            _ => None,
        }
    }
}

fn parse_window_level(s: &str) -> window::Level {
    match s {
        "always_on_top" => window::Level::AlwaysOnTop,
        "always_on_bottom" => window::Level::AlwaysOnBottom,
        _ => window::Level::Normal,
    }
}

fn parse_window_mode(v: &serde_json::Value) -> window::Mode {
    match v.get("mode").and_then(|v| v.as_str()).unwrap_or("windowed") {
        "fullscreen" => window::Mode::Fullscreen,
        "hidden" => window::Mode::Hidden,
        _ => window::Mode::Windowed,
    }
}

fn parse_direction(s: &str) -> window::Direction {
    match s {
        "north" => window::Direction::North,
        "south" => window::Direction::South,
        "east" => window::Direction::East,
        "west" => window::Direction::West,
        "north_east" => window::Direction::NorthEast,
        "north_west" => window::Direction::NorthWest,
        "south_east" => window::Direction::SouthEast,
        "south_west" => window::Direction::SouthWest,
        _ => window::Direction::SouthEast,
    }
}

// ---------------------------------------------------------------------------
// Key serialization helpers
// ---------------------------------------------------------------------------

fn serialize_key(key: &iced::keyboard::Key) -> String {
    match key {
        iced::keyboard::Key::Named(named) => format!("{named:?}"),
        iced::keyboard::Key::Character(c) => c.to_string(),
        iced::keyboard::Key::Unidentified => "Unidentified".to_string(),
    }
}

fn serialize_modifiers(mods: iced::keyboard::Modifiers) -> KeyModifiers {
    KeyModifiers {
        shift: mods.shift(),
        ctrl: mods.control(),
        alt: mods.alt(),
        logo: mods.logo(),
        command: mods.command(),
    }
}

// ---------------------------------------------------------------------------
// Mouse serialization helpers
// ---------------------------------------------------------------------------

fn serialize_mouse_button(button: &iced::mouse::Button) -> String {
    match button {
        iced::mouse::Button::Left => "left".to_string(),
        iced::mouse::Button::Right => "right".to_string(),
        iced::mouse::Button::Middle => "middle".to_string(),
        iced::mouse::Button::Back => "back".to_string(),
        iced::mouse::Button::Forward => "forward".to_string(),
        iced::mouse::Button::Other(n) => format!("other_{n}"),
    }
}

fn serialize_scroll_delta(delta: &iced::mouse::ScrollDelta) -> (f32, f32, &'static str) {
    match delta {
        iced::mouse::ScrollDelta::Lines { x, y } => (*x, *y, "lines"),
        iced::mouse::ScrollDelta::Pixels { x, y } => (*x, *y, "pixels"),
    }
}

// ---------------------------------------------------------------------------
// stdout event emitter
// ---------------------------------------------------------------------------

fn emit_event(event: OutgoingEvent) {
    match serde_json::to_string(&event) {
        Ok(json) => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            if let Err(e) = writeln!(handle, "{json}") {
                eprintln!("julep_gui: failed to write event to stdout: {e}");
            }
            let _ = handle.flush();
        }
        Err(e) => eprintln!("julep_gui: failed to serialize event: {e}"),
    }
}

// ---------------------------------------------------------------------------
// stdout effect response emitter
// ---------------------------------------------------------------------------

fn emit_effect_response(response: protocol::EffectResponse) {
    match serde_json::to_string(&response) {
        Ok(json) => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            if let Err(e) = writeln!(handle, "{json}") {
                eprintln!("julep_gui: failed to write effect response to stdout: {e}");
            }
            let _ = handle.flush();
        }
        Err(e) => eprintln!("julep_gui: failed to serialize effect response: {e}"),
    }
}

// ---------------------------------------------------------------------------
// stdin reader thread
// ---------------------------------------------------------------------------

fn spawn_stdin_reader(sender: Sender<StdinEvent>) {
    thread::spawn(move || {
        let stdin = io::stdin();
        let reader = io::BufReader::new(stdin.lock());

        for line in reader.lines() {
            match line {
                Ok(raw) => {
                    let trimmed = raw.trim();
                    if trimmed.is_empty() {
                        continue;
                    }
                    match serde_json::from_str::<IncomingMessage>(trimmed) {
                        Ok(msg) => {
                            if sender.send(StdinEvent::Message(msg)).is_err() {
                                return;
                            }
                        }
                        Err(e) => {
                            let warning = format!("parse error: {e} (input: {trimmed})");
                            if sender.send(StdinEvent::Warning(warning)).is_err() {
                                return;
                            }
                        }
                    }
                }
                Err(e) => {
                    let _ = sender.send(StdinEvent::Warning(format!("read error: {e}")));
                    break;
                }
            }
        }

        let _ = sender.send(StdinEvent::Closed);
    });
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() -> iced::Result {
    // The boot closure must be `Fn`, but channel setup must only happen once.
    // Use a Mutex<Option<Receiver>> captured in the closure: the first call
    // takes the receiver out; subsequent calls (which iced never makes) get a
    // dummy channel to satisfy the type system.
    use std::sync::Mutex;

    let (tx, rx) = mpsc::channel::<StdinEvent>();
    spawn_stdin_reader(tx);

    let rx_slot: Mutex<Option<Receiver<StdinEvent>>> = Mutex::new(Some(rx));

    iced::daemon(
        move || {
            let rx = rx_slot
                .lock()
                .expect("rx_slot lock poisoned")
                .take()
                .unwrap_or_else(|| {
                    eprintln!("julep_gui: boot called more than once -- this is a bug");
                    mpsc::channel().1
                });
            (App::new(rx), Task::none())
        },
        App::update,
        App::view_window,
    )
    .title(App::title_for_window)
    .subscription(App::subscription)
    .theme(App::theme_for_window)
    .run()
}
