mod effects;
mod protocol;
mod theming;
mod tree;
mod widgets;

use std::collections::{HashMap, HashSet};
use std::io::{self, BufRead, Write};
use std::sync::mpsc::{self, Receiver, Sender};
use std::thread;
use std::time::Duration;

use iced::widget::{container, markdown, text, text_editor};
use iced::{event, time, window, Element, Fill, Subscription, Task, Theme};

use protocol::{IncomingMessage, KeyModifiers, OutgoingEvent};
use tree::Tree;

// ---------------------------------------------------------------------------
// Message
// ---------------------------------------------------------------------------

#[derive(Debug, Clone)]
enum Message {
    /// A user clicked a button with the given node ID.
    Click(String),
    /// A text input value changed (id, new_value).
    Input(String, String),
    /// A text input was submitted (id, current_value).
    Submit(String, String),
    /// A checkbox or toggler was toggled (id, checked).
    Toggle(String, bool),
    /// A slider value changed (id, value).
    Slide(String, f64),
    /// A slider was released (id, value).
    SlideRelease(String, f64),
    /// A pick_list/combo_box/radio selection (id, value).
    Select(String, String),
    /// A text editor action (id, action).
    TextEditorAction(String, text_editor::Action),
    /// A markdown link was clicked.
    MarkdownUrl(markdown::Uri),
    /// Periodic tick used to drain the inbound channel.
    Tick,
    /// A keyboard key was pressed.
    KeyPressed(iced::keyboard::Key, iced::keyboard::Modifiers),
    /// A keyboard key was released.
    KeyReleased(iced::keyboard::Key, iced::keyboard::Modifiers),
    /// A window close was requested by the user (WM close button).
    WindowCloseRequested(window::Id),
    /// A window was actually closed by iced.
    WindowClosed(window::Id),
    /// A new window was opened (iced_id, julep_id).
    WindowOpened(window::Id, String),
}

// ---------------------------------------------------------------------------
// App state
// ---------------------------------------------------------------------------

struct App {
    tree: Tree,
    theme: Theme,
    receiver: Receiver<StdinEvent>,
    stdin_closed: bool,
    /// Persistent state for text_editor widgets, keyed by node ID.
    editor_contents: HashMap<String, text_editor::Content>,
    /// Cached parsed markdown items, keyed by node ID.
    markdown_items: HashMap<String, Vec<markdown::Item>>,
    /// Tasks generated by apply() that must be returned from update().
    pending_tasks: Vec<Task<Message>>,
    /// Active subscriptions: kind -> tag.
    active_subscriptions: HashMap<String, String>,
    /// Julep window ID -> iced window ID.
    window_map: HashMap<String, window::Id>,
    /// Iced window ID -> julep window ID.
    reverse_window_map: HashMap<window::Id, String>,
}

/// What the stdin reader thread sends back.
#[derive(Debug)]
enum StdinEvent {
    Message(IncomingMessage),
    Closed,
    Warning(String),
}

impl App {
    fn new(receiver: Receiver<StdinEvent>) -> Self {
        Self {
            tree: Tree::new(),
            theme: Theme::Dark,
            receiver,
            stdin_closed: false,
            editor_contents: HashMap::new(),
            markdown_items: HashMap::new(),
            pending_tasks: Vec::new(),
            active_subscriptions: HashMap::new(),
            window_map: HashMap::new(),
            reverse_window_map: HashMap::new(),
        }
    }

    fn title_for_window(&self, window_id: window::Id) -> String {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id) {
            if let Some(node) = self.tree.find_window(julep_id) {
                if let Some(title) = node.props.get("title").and_then(|v| v.as_str()) {
                    return title.to_string();
                }
            }
        }
        "Julep".to_string()
    }

    fn theme_for_window(&self, window_id: window::Id) -> Theme {
        if let Some(julep_id) = self.reverse_window_map.get(&window_id) {
            if let Some(node) = self.tree.find_window(julep_id) {
                if let Some(theme_val) = node.props.get("theme") {
                    return theming::resolve_theme(theme_val);
                }
            }
        }
        self.theme.clone()
    }

    fn update(&mut self, message: Message) -> Task<Message> {
        match message {
            Message::Tick => {
                self.drain_stdin();
                let tasks: Vec<Task<Message>> = self.pending_tasks.drain(..).collect();
                let mut batch = Task::batch(tasks);
                if self.stdin_closed {
                    batch = batch.chain(iced::exit());
                }
                batch
            }
            Message::Click(id) => {
                emit_event(OutgoingEvent::click(id));
                Task::none()
            }
            Message::Input(id, value) => {
                emit_event(OutgoingEvent::input(id, value));
                Task::none()
            }
            Message::Submit(id, value) => {
                emit_event(OutgoingEvent::submit(id, value));
                Task::none()
            }
            Message::Toggle(id, value) => {
                emit_event(OutgoingEvent::toggle(id, value));
                Task::none()
            }
            Message::Slide(id, value) => {
                emit_event(OutgoingEvent::slide(id, value));
                Task::none()
            }
            Message::SlideRelease(id, value) => {
                emit_event(OutgoingEvent::slide_release(id, value));
                Task::none()
            }
            Message::Select(id, value) => {
                emit_event(OutgoingEvent::select(id, value));
                Task::none()
            }
            Message::TextEditorAction(id, action) => {
                let is_edit = action.is_edit();
                if let Some(content) = self.editor_contents.get_mut(&id) {
                    content.perform(action);
                    if is_edit {
                        let new_text = content.text();
                        emit_event(OutgoingEvent::input(id, new_text));
                    }
                }
                Task::none()
            }
            Message::MarkdownUrl(url) => {
                eprintln!("julep_gui: markdown link clicked: {url}");
                Task::none()
            }
            Message::KeyPressed(key, mods) => {
                if let Some(tag) = self.active_subscriptions.get("on_key_press") {
                    let key_str = serialize_key(&key);
                    emit_event(OutgoingEvent::key_press(
                        tag.clone(),
                        key_str,
                        serialize_modifiers(mods),
                    ));
                }
                Task::none()
            }
            Message::KeyReleased(key, mods) => {
                if let Some(tag) = self.active_subscriptions.get("on_key_release") {
                    let key_str = serialize_key(&key);
                    emit_event(OutgoingEvent::key_release(
                        tag.clone(),
                        key_str,
                        serialize_modifiers(mods),
                    ));
                }
                Task::none()
            }
            Message::WindowCloseRequested(window_id) => {
                if let Some(tag) = self.active_subscriptions.get("on_window_close") {
                    emit_event(OutgoingEvent::window_close(tag.clone()));
                }
                // Remove from maps if this was a julep-managed window.
                if let Some(julep_id) = self.reverse_window_map.remove(&window_id) {
                    self.window_map.remove(&julep_id);
                }
                window::close(window_id)
            }
            Message::WindowClosed(window_id) => {
                // Clean up maps when iced confirms a window has closed.
                if let Some(julep_id) = self.reverse_window_map.remove(&window_id) {
                    self.window_map.remove(&julep_id);
                    eprintln!("julep_gui: window closed: {julep_id}");
                }
                Task::none()
            }
            Message::WindowOpened(iced_id, julep_id) => {
                eprintln!("julep_gui: window opened: {julep_id} -> {iced_id:?}");
                self.window_map.insert(julep_id.clone(), iced_id);
                self.reverse_window_map.insert(iced_id, julep_id);
                Task::none()
            }
        }
    }

    fn view_window(&self, window_id: window::Id) -> Element<'_, Message> {
        let julep_id = match self.reverse_window_map.get(&window_id) {
            Some(id) => id,
            None => {
                return container(text("unknown window"))
                    .width(Fill)
                    .height(Fill)
                    .center(Fill)
                    .into();
            }
        };

        match self.tree.find_window(julep_id) {
            Some(window_node) => {
                widgets::render(window_node, &self.editor_contents, &self.markdown_items)
            }
            None => container(text("waiting for snapshot..."))
                .width(Fill)
                .height(Fill)
                .center(Fill)
                .into(),
        }
    }

    fn subscription(&self) -> Subscription<Message> {
        let mut subs = vec![
            time::every(Duration::from_millis(16)).map(|_| Message::Tick),
            // Always listen for window close events so we can clean up maps.
            window::close_events().map(Message::WindowClosed),
        ];

        if self.active_subscriptions.contains_key("on_key_press") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyPressed {
                    key,
                    modifiers,
                    ..
                }) = evt
                {
                    Some(Message::KeyPressed(key, modifiers))
                } else {
                    None
                }
            }));
        }

        if self.active_subscriptions.contains_key("on_key_release") {
            subs.push(event::listen_with(|evt, _status, _window| {
                if let iced::Event::Keyboard(iced::keyboard::Event::KeyReleased {
                    key,
                    modifiers,
                    ..
                }) = evt
                {
                    Some(Message::KeyReleased(key, modifiers))
                } else {
                    None
                }
            }));
        }

        if self.active_subscriptions.contains_key("on_window_close") {
            subs.push(window::close_requests().map(Message::WindowCloseRequested));
        }

        Subscription::batch(subs)
    }

    /// Drain all pending messages from the stdin channel and apply them.
    fn drain_stdin(&mut self) {
        loop {
            match self.receiver.try_recv() {
                Ok(StdinEvent::Message(incoming)) => {
                    self.apply(incoming);
                }
                Ok(StdinEvent::Warning(msg)) => {
                    eprintln!("julep_gui: stdin warning: {msg}");
                }
                Ok(StdinEvent::Closed) => {
                    eprintln!("julep_gui: stdin closed -- exiting");
                    self.stdin_closed = true;
                    break;
                }
                Err(mpsc::TryRecvError::Empty) => break,
                Err(mpsc::TryRecvError::Disconnected) => {
                    eprintln!("julep_gui: stdin reader disconnected -- exiting");
                    self.stdin_closed = true;
                    break;
                }
            }
        }
    }

    fn apply(&mut self, message: IncomingMessage) {
        match message {
            IncomingMessage::Snapshot { tree } => {
                eprintln!("julep_gui: snapshot received (root id={})", tree.id);
                if let Some(theme_val) = tree.props.get("theme") {
                    self.theme = theming::resolve_theme(theme_val);
                }
                self.tree.snapshot(tree);
                // Clear stale caches and pre-populate for the new tree.
                self.editor_contents.clear();
                self.markdown_items.clear();
                if let Some(root) = self.tree.root() {
                    widgets::ensure_caches(
                        root,
                        &mut self.editor_contents,
                        &mut self.markdown_items,
                    );
                }
                // Sync windows to match the new tree.
                let task = self.sync_windows();
                self.pending_tasks.push(task);
            }
            IncomingMessage::Patch { ops } => {
                eprintln!("julep_gui: patch received ({} ops)", ops.len());
                self.tree.apply_patch(ops);
                // Re-populate caches in case patch added new stateful nodes.
                if let Some(root) = self.tree.root() {
                    widgets::ensure_caches(
                        root,
                        &mut self.editor_contents,
                        &mut self.markdown_items,
                    );
                }
                // Sync windows in case the patch changed the window set.
                let task = self.sync_windows();
                self.pending_tasks.push(task);
            }
            IncomingMessage::EffectRequest { id, kind, payload } => {
                eprintln!("julep_gui: effect request: {kind} ({id})");
                let response = effects::handle_effect(id, &kind, &payload);
                emit_effect_response(response);
            }
            IncomingMessage::WidgetOp { op, payload } => {
                eprintln!("julep_gui: widget_op: {op}");
                let task = match op.as_str() {
                    "focus" => {
                        let target = payload
                            .get("target")
                            .and_then(|v| v.as_str())
                            .unwrap_or_default()
                            .to_string();
                        iced::widget::operation::focus::<Message>(
                            iced::widget::Id::from(target),
                        )
                    }
                    "focus_next" => iced::widget::operation::focus_next(),
                    "focus_previous" => iced::widget::operation::focus_previous(),
                    "scroll_to" => {
                        let target = payload
                            .get("target")
                            .and_then(|v| v.as_str())
                            .unwrap_or_default()
                            .to_string();
                        let offset_y = payload
                            .get("offset")
                            .and_then(|v| v.as_f64())
                            .unwrap_or(0.0) as f32;
                        iced::widget::operation::scroll_to(
                            iced::widget::Id::from(target),
                            iced::widget::operation::AbsoluteOffset { x: 0.0, y: offset_y },
                        )
                    }
                    "close_window" => {
                        // Close the oldest (main) window, which triggers app exit.
                        window::oldest().and_then(|id| {
                            window::close(id)
                        })
                    }
                    "select_all" => {
                        let target = payload
                            .get("target")
                            .and_then(|v| v.as_str())
                            .unwrap_or_default()
                            .to_string();
                        iced::widget::operation::select_all(
                            iced::widget::Id::from(target),
                        )
                    }
                    other => {
                        eprintln!("julep_gui: unknown widget_op: {other}");
                        Task::none()
                    }
                };
                self.pending_tasks.push(task);
            }
            IncomingMessage::SubscriptionRegister { kind, tag } => {
                eprintln!("julep_gui: subscription register: {kind} -> {tag}");
                self.active_subscriptions.insert(kind, tag);
            }
            IncomingMessage::SubscriptionUnregister { kind } => {
                eprintln!("julep_gui: subscription unregister: {kind}");
                self.active_subscriptions.remove(&kind);
            }
            IncomingMessage::WindowOp {
                op,
                window_id,
                settings,
            } => {
                eprintln!("julep_gui: window_op: {op} ({window_id})");
                match op.as_str() {
                    "open" => {
                        let width = settings
                            .get("width")
                            .and_then(|v| v.as_f64())
                            .unwrap_or(800.0) as f32;
                        let height = settings
                            .get("height")
                            .and_then(|v| v.as_f64())
                            .unwrap_or(600.0) as f32;

                        let win_settings = window::Settings {
                            size: iced::Size::new(width, height),
                            ..window::Settings::default()
                        };

                        let (iced_id, open_task) = window::open(win_settings);

                        self.window_map.insert(window_id.clone(), iced_id);
                        self.reverse_window_map.insert(iced_id, window_id.clone());

                        let julep_id = window_id;
                        let task = open_task.map(move |id| Message::WindowOpened(id, julep_id.clone()));
                        self.pending_tasks.push(task);
                    }
                    "close" => {
                        if let Some(iced_id) = self.window_map.remove(&window_id) {
                            self.reverse_window_map.remove(&iced_id);
                            self.pending_tasks.push(window::close(iced_id));
                        } else {
                            eprintln!(
                                "julep_gui: window_op close: unknown window_id: {window_id}"
                            );
                        }
                    }
                    other => {
                        eprintln!("julep_gui: unknown window_op: {other}");
                    }
                }
            }
        }
    }

    /// Compare the set of window nodes in the tree against the currently open
    /// windows and open/close as needed.
    fn sync_windows(&mut self) -> Task<Message> {
        let tree_windows: HashSet<String> = self.tree.window_ids().into_iter().collect();
        let open_windows: HashSet<String> = self.window_map.keys().cloned().collect();

        let mut tasks = Vec::new();

        // Open windows that exist in the tree but are not yet open.
        for win_id in &tree_windows {
            if !open_windows.contains(win_id) {
                let settings = self.window_settings_for(win_id);
                let (iced_id, open_task) = window::open(settings);
                self.window_map.insert(win_id.clone(), iced_id);
                self.reverse_window_map.insert(iced_id, win_id.clone());

                let julep_id = win_id.clone();
                tasks.push(
                    open_task.map(move |id| Message::WindowOpened(id, julep_id.clone())),
                );
            }
        }

        // Close windows that are open but no longer in the tree.
        for win_id in &open_windows {
            if !tree_windows.contains(win_id) {
                if let Some(iced_id) = self.window_map.remove(win_id) {
                    self.reverse_window_map.remove(&iced_id);
                    tasks.push(window::close(iced_id));
                }
            }
        }

        Task::batch(tasks)
    }

    /// Build window::Settings from a window node's props.
    fn window_settings_for(&self, julep_id: &str) -> window::Settings {
        let mut width = 800.0_f32;
        let mut height = 600.0_f32;

        if let Some(node) = self.tree.find_window(julep_id) {
            if let Some(w) = node.props.get("width").and_then(|v| v.as_f64()) {
                width = w as f32;
            }
            if let Some(h) = node.props.get("height").and_then(|v| v.as_f64()) {
                height = h as f32;
            }
        }

        window::Settings {
            size: iced::Size::new(width, height),
            ..window::Settings::default()
        }
    }
}

// ---------------------------------------------------------------------------
// Key serialization helpers
// ---------------------------------------------------------------------------

fn serialize_key(key: &iced::keyboard::Key) -> String {
    match key {
        iced::keyboard::Key::Named(named) => format!("{named:?}"),
        iced::keyboard::Key::Character(c) => c.to_string(),
        iced::keyboard::Key::Unidentified => "Unidentified".to_string(),
    }
}

fn serialize_modifiers(mods: iced::keyboard::Modifiers) -> KeyModifiers {
    KeyModifiers {
        shift: mods.shift(),
        ctrl: mods.control(),
        alt: mods.alt(),
        logo: mods.logo(),
    }
}

// ---------------------------------------------------------------------------
// stdout event emitter
// ---------------------------------------------------------------------------

fn emit_event(event: OutgoingEvent) {
    match serde_json::to_string(&event) {
        Ok(json) => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            if let Err(e) = writeln!(handle, "{json}") {
                eprintln!("julep_gui: failed to write event to stdout: {e}");
            }
            let _ = handle.flush();
        }
        Err(e) => eprintln!("julep_gui: failed to serialize event: {e}"),
    }
}

// ---------------------------------------------------------------------------
// stdout effect response emitter
// ---------------------------------------------------------------------------

fn emit_effect_response(response: protocol::EffectResponse) {
    match serde_json::to_string(&response) {
        Ok(json) => {
            let stdout = io::stdout();
            let mut handle = stdout.lock();
            if let Err(e) = writeln!(handle, "{json}") {
                eprintln!("julep_gui: failed to write effect response to stdout: {e}");
            }
            let _ = handle.flush();
        }
        Err(e) => eprintln!("julep_gui: failed to serialize effect response: {e}"),
    }
}

// ---------------------------------------------------------------------------
// stdin reader thread
// ---------------------------------------------------------------------------

fn spawn_stdin_reader(sender: Sender<StdinEvent>) {
    thread::spawn(move || {
        let stdin = io::stdin();
        let reader = io::BufReader::new(stdin.lock());

        for line in reader.lines() {
            match line {
                Ok(raw) => {
                    let trimmed = raw.trim();
                    if trimmed.is_empty() {
                        continue;
                    }
                    match serde_json::from_str::<IncomingMessage>(trimmed) {
                        Ok(msg) => {
                            if sender.send(StdinEvent::Message(msg)).is_err() {
                                return;
                            }
                        }
                        Err(e) => {
                            let warning = format!("parse error: {e} (input: {trimmed})");
                            if sender.send(StdinEvent::Warning(warning)).is_err() {
                                return;
                            }
                        }
                    }
                }
                Err(e) => {
                    let _ = sender.send(StdinEvent::Warning(format!("read error: {e}")));
                    break;
                }
            }
        }

        let _ = sender.send(StdinEvent::Closed);
    });
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

fn main() -> iced::Result {
    // The boot closure must be `Fn`, but channel setup must only happen once.
    // Use a Mutex<Option<Receiver>> captured in the closure: the first call
    // takes the receiver out; subsequent calls (which iced never makes) get a
    // dummy channel to satisfy the type system.
    use std::sync::Mutex;

    let (tx, rx) = mpsc::channel::<StdinEvent>();
    spawn_stdin_reader(tx);

    let rx_slot: Mutex<Option<Receiver<StdinEvent>>> = Mutex::new(Some(rx));

    iced::daemon(
        move || {
            let rx = rx_slot
                .lock()
                .expect("rx_slot lock poisoned")
                .take()
                .unwrap_or_else(|| {
                    eprintln!("julep_gui: boot called more than once -- this is a bug");
                    mpsc::channel().1
                });
            (App::new(rx), Task::none())
        },
        App::update,
        App::view_window,
    )
    .title(App::title_for_window)
    .subscription(App::subscription)
    .theme(App::theme_for_window)
    .run()
}
